sudo: required
services:
  - docker


before_install:
  - docker build -t mynameisgan10/docker-react-practice -f Dockerfile.dev . 


script:
  - docker run mynameisgan10/docker-react-practice npm run test -- --coverage