sudo: required
services:
  - docker


before_install:
  - docker build -t mynameisgan10/docker-react-practice -f Dockerfile.dev . 


script:
  - docker run -e CI=true mynameisgan10/docker-react-practice npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-practice"
  env: "DockerReactPractice-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-031599091231"
  bucket_path: "docker-react-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


